USE PROYECTO_PRUEBA_PRODUCTOS


CREATE TABLE CATEGORY (
ID_CATEGORY INT PRIMARY KEY IDENTITY (1,1),
CODE_CATEGORY NVARCHAR (100)UNIQUE,
CATEGORY_NAME NVARCHAR (100)UNIQUE
)

CREATE TABLE SUPPLIER (
ID_SUPPLIER INT PRIMARY KEY IDENTITY (1,1),
SUPPLIER_CODE NVARCHAR (100)UNIQUE,
SUPPLIER_NAME NVARCHAR (100)UNIQUE
)

CREATE TABLE PRODUCT (
ID_PRODUCT INT PRIMARY KEY IDENTITY (1,1),
PRODUCT_CODE NVARCHAR (100)UNIQUE,
PRODUCT_NAME NVARCHAR (100),
PRODUCT_DESCRIPTION NVARCHAR (255),
ID_SUPPLIER INT,
PRICE DECIMAL (10,2),
ID_CATEGORY INT,
FOREIGN KEY (ID_SUPPLIER) REFERENCES SUPPLIER (ID_SUPPLIER),
FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY (ID_CATEGORY)
)

CREATE TABLE IMAGE_PRODUCT (
ID_IMAGE INT PRIMARY KEY IDENTITY (1,1),
ID_PRODUCT INT,
IMAGE_NAME NVARCHAR(100),
PRODUCT_IMAGE VARBINARY(MAX),
FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT)

)


CREATE TABLE STOCK (
ID_STOCK INT PRIMARY KEY IDENTITY(1,1),
ID_PRODUCT INT,
QUANTITY INT,
FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT)
)



