
package cr.ac.una.proyectobd.presentation.product;

import cr.ac.una.proyectobd.domain.Category;
import cr.ac.una.proyectobd.domain.Product;
import cr.ac.una.proyectobd.domain.Supplier;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Briones
 */
public class viewEditProduct extends javax.swing.JFrame {

    private String urlImage = "";
    private Product p;
    /**
     * Creates new form wie
     */
    public viewEditProduct(Product p) {
        this.p = p;
        initComponents();
        uploadCB();
        uploadData();
    }

    private void clearFilds() {
        tNameProduct.setText("");
        tDescription.setText("");
        cbSupplier.setSelectedIndex(0);
        tPrice.setText("");
        tQuantity.setText("");
        cbCategory.setSelectedIndex(0);
    }

    private void uploadCB() {
//        Traer los datos de la base de datos
        ArrayList<Supplier> listSupplier = new ArrayList<>();
        listSupplier.add(new Supplier(1, "Proveedor 1"));
        
        cbSupplier.removeAllItems();
        cbSupplier.addItem(new Supplier(0, "Ninguno"));
        for (Supplier supplier : listSupplier) {
            cbSupplier.addItem(supplier);
        }
        
        ArrayList<Category> listCategory = new ArrayList<>();
        listCategory.add(new Category(1, "Categoria 1"));
        cbCategory.removeAllItems();
        cbCategory.addItem(new Category(0, "Ninguna"));
        for (Category category : listCategory) {
            cbCategory.addItem(category);
        }
        
    }
    
    private void uploadData(){
        tNameProduct.setText(this.p.getName());
        tDescription.setText("");
        cbSupplier.setSelectedIndex(0);
        tPrice.setText("");
        tQuantity.setText("");
        cbCategory.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        tNameProduct = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbSupplier = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tQuantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnUploadImage = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lNameImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar producto");

        jLabel1.setText("Nombre");

        tNameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNameProductActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripción");

        tDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDescriptionActionPerformed(evt);
            }
        });

        jLabel3.setText("Proveedor");

        jLabel4.setText("Precio");

        jLabel5.setText("Cantidad");

        jLabel6.setText("Categoria");

        cbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoryActionPerformed(evt);
            }
        });

        jLabel7.setText("Subir imagen");

        btnUploadImage.setText("Subir imagen");
        btnUploadImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUploadImageMouseClicked(evt);
            }
        });
        btnUploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadImageActionPerformed(evt);
            }
        });

        btnModify.setText("Modificar");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        lNameImage.setText("Ningúna imagen seleccionada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tNameProduct)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tPrice))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnUploadImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tDescription)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(tQuantity)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 12, Short.MAX_VALUE))
                                    .addComponent(cbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lNameImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUploadImage)
                    .addComponent(lNameImage))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModify)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNameProductActionPerformed

    private void tDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDescriptionActionPerformed

    private void cbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoryActionPerformed

    private void btnUploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadImageActionPerformed

    private void btnUploadImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadImageMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            public boolean accept(File f) {
                return f.getName().toLowerCase().endsWith(".jpg")
                        || f.getName().toLowerCase().endsWith(".jpeg")
                        || f.getName().toLowerCase().endsWith(".png")
                        || f.isDirectory();
            }

            public String getDescription() {
                return "Archivos de Imagen";
            }
        });

        // Mostrar el diálogo para seleccionar archivos
        int result = fileChooser.showOpenDialog(viewEditProduct.this);

        // Si el usuario selecciona un archivo
        if (result == JFileChooser.APPROVE_OPTION) {
            // Obtener la ruta del archivo seleccionado
            File fileSelected = fileChooser.getSelectedFile();
            String path = fileSelected.getAbsolutePath();
            urlImage = fileSelected.getName();

            lNameImage.setText(fileSelected.getName());
            JOptionPane.showMessageDialog(null, path);
        }
    }//GEN-LAST:event_btnUploadImageMouseClicked

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        try {
            String name = tNameProduct.getText();
            String description = tDescription.getText();
            Supplier supplier = (Supplier) cbSupplier.getSelectedItem();
            double price = Double.parseDouble(tPrice.getText());
            int quantity = Integer.parseInt(tQuantity.getText());
            Category category = (Category) cbCategory.getSelectedItem();

            if (name.trim().isEmpty() || description.trim().isEmpty() || supplier == null || price <= 0
                    || category == null || quantity <= 0 || urlImage.trim().isEmpty() || 
                    cbSupplier.getSelectedIndex() == 0 || cbCategory.getSelectedIndex() == 0) {

                JOptionPane.showMessageDialog(null, "Favor llenar todos los campos");
                return;
            }

            //Editar en BD
            JOptionPane.showMessageDialog(null, "Editar en BD");
//          Actualizar los valores en el objeto
            //this.p.setName(name);
            
            
//          Si todo es correcto limpiar variables y campos
            urlImage = "";
            lNameImage.setText("Ningúna imagen seleccionada");
            clearFilds();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El precio y cantidad deben ser de tipo numérico");
        }

    }                                         


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnUploadImage;
    private javax.swing.JComboBox<Category> cbCategory;
    private javax.swing.JComboBox<Supplier> cbSupplier;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lNameImage;
    private javax.swing.JTextField tDescription;
    private javax.swing.JTextField tNameProduct;
    private javax.swing.JTextField tPrice;
    private javax.swing.JTextField tQuantity;
    // End of variables declaration//GEN-END:variables
}

