/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cr.ac.una.proyectobd.presentation.cliente;

/**
 *
 * @author Carlos Orellana
 */
public class viewCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewCliente
     */
    public viewCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfSegundoApellido = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfPrimerApellido1 = new javax.swing.JTextField();
        jCBXProvincia = new javax.swing.JComboBox<>();
        tfSegundoApellido1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jButtonActualizarCliente = new javax.swing.JButton();
        jButtonEliminarCliente = new javax.swing.JButton();
        jButtonCrearCliente2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion de Clientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setText("Primer Apellido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel3.setText("Segundo Apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel4.setText("Provincia");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jLabel5.setText("Calle");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 40, -1));
        getContentPane().add(tfSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 110, -1));
        getContentPane().add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, -1));
        getContentPane().add(tfPrimerApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 110, -1));

        jCBXProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San Jose", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Puntarenas", "Limón" }));
        getContentPane().add(jCBXProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));
        getContentPane().add(tfSegundoApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 110, -1));

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Primer Apellido", "Segundo Apellido", "Provincia", "Calle"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 700, 340));

        jButtonActualizarCliente.setText("Actualizar");
        getContentPane().add(jButtonActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 110, -1));

        jButtonEliminarCliente.setText("Eliminar");
        getContentPane().add(jButtonEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 110, -1));

        jButtonCrearCliente2.setText("Crear Cliente");
        getContentPane().add(jButtonCrearCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizarCliente;
    private javax.swing.JButton jButtonCrearCliente2;
    private javax.swing.JButton jButtonEliminarCliente;
    private javax.swing.JComboBox<String> jCBXProvincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPrimerApellido1;
    private javax.swing.JTextField tfSegundoApellido;
    private javax.swing.JTextField tfSegundoApellido1;
    // End of variables declaration//GEN-END:variables
}
